server:
  port: 8083

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-server
  profiles:
    active: local
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: =============== Spring Cloud Gateway Global Filter ===============
            preLogger: true
            postLogger: true
            endMessage: ====================================================================
      routes:
          # actuator
        - id: user-service
          uri: http://localhost:8080/
          predicates:
            - Path=/user-service/actuator/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

          # 로그인
        - id: user-service
          uri: http://localhost:8080/
          predicates:
            - Path=/user-service/auth/sign-in
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

          # 회원가입
        - id: user-service
          uri: http://localhost:8080/
          predicates:
            - Path=/user-service/api/v1/users/**
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

          # 토큰 재발급
        - id: user-service
          uri: http://localhost:8080/
          predicates:
            - Path=/user-service/api/v1/users/{userId}/reissue
            - Method=GET
          filters:
            - RewritePath=/user-service/api/v1/users/(?<userId>.*)/reissue, /api/v1/users/$\{userId}/reissue

          # user-service 공통
        - id: user-service
          uri: http://localhost:8080/
          predicates:
            - Path=/user-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - name: AuthorizationHeaderFilter # 테스트 시 주석처리

          # actuator
        - id: order-service
          uri: http://localhost:8081/
          predicates:
            - Path=/order-service/actuator/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/order-service/(?<segment>.*), /$\{segment}

          # order-service 공통
        - id: order-service
          uri: http://localhost:8081/
          predicates:
            - Path=/order-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/order-service/(?<segment>.*), /$\{segment}
            - name: AuthorizationHeaderFilter # 테스트 시 주석처리

          # actuator
        - id: product-service
          uri: http://localhost:8082/
          predicates:
            - Path=/product-service/actuator/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/product-service/(?<segment>.*), /$\{segment}

        # 상품 등록 - 관리자 권한
        - id : product-service
          uri: http://localhost:8082/
          predicates:
            - Path=/product-service/api/v1/products
            - Method=PUT,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/product-service/(?<segment>.*), /$\{segment}
            - name: AdminAccessFilter # 테스트 시 주석처리
            - name: AuthorizationHeaderFilter # 테스트 시 주석처리

        # product-service 공통
        - id: product-service
          uri: http://localhost:8082/
          predicates:
            - Path=/product-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/product-service/(?<segment>.*), /$\{segment}
            - name: AuthorizationHeaderFilter # 테스트 시 주석처리

        # actuator
        - id: pay-service
          uri: http://localhost:8084/
          predicates:
            - Path=/pay-service/actuator/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/pay-service/(?<segment>.*), /$\{segment}

        # product-service 공통
        - id: pay-service
          uri: http://localhost:8084/
          predicates:
            - Path=/pay-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/pay-service/(?<segment>.*), /$\{segment}
            - name: AuthorizationHeaderFilter # 테스트 시 주석처리

logging:
  level:
    com.bootakhae.gatewayserver: DEBUG

token:
  access-expired-time: ${access-expired-time}
  refresh-expired-time: ${refresh-expired-time}
  secret: ${token-secret}