server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mariadb://localhost:13306/mydb
    driver-class-name: org.mariadb.jdbc.Driver
    username: ENC(5HP1L75+qdxzh5XMehSs0A==)
    password: ENC(JpgMqXVM384ILrWyE44M6c1rScTkMjb5)
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    host: ENC(KJNWE3KjMxd9qeTi4EQ071FEUYPqIoy9) # ${mail-host} #SMTP 호스트 서버
    port: 587 #SMTP 서버 포트
    username: ENC(dXsmeRaz3vhCqmooJ1YR/LbXE2py39kB) #${mail.username_} # 발신자 이메일 ex) test@gmail.com - test
    password: ENC(D0dmU4h2Ij0JZT/PzFjFDE8Leu5962oLyFZ/K4KSS8s=) #${mail.password} # App password
    properties:
      mail:
        smtp:
          starttls:
            enable: true # startTLS 활성화 여부 (기본값: false)
          auth: true # 사용자 인증 시도 여부 (기본값 : false)
          timeout: ENC(iBn4LqVcw1uCw+KAjy2mhA==) # ${smtp-timeout} # Socket Read Timeout 시간 (기본값 : 무한)

management:
  endpoints:
    web:
      exposure:
        include: info, refresh, health, beans, busrefresh, circuitbreakers

# OTP TTL 시간 
redis:
  otp:
    ttl: 180
  refresh-token:
    ttl: 86400

# 개인정보 암호화
aes:
  spec: ENC(Mlkv6nlVoCV3NObsk/SQcw==)
  key: ENC(Na9mPy7vTY7oemJWspK4n3jqzB9mQJBj1kj4ory9IpFkwlLivkqLMlSGhLIhDicD)

logging:
  level:
    com.bootakhae.userservice: DEBUG
