server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: user-service
  profiles:
    active: local
  datasource:
    url: ${url}
    driver-class-name: ${driver-class-name}
    username: ${username_}
    password: ${password}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  mail:
    host: ${mail-host} #SMTP 호스트 서버
    port: ${mail-port} #SMTP 서버 포트
    username: ${mail.username_} # 발신자 이메일 ex) test@gmail.com - test
    password: ${mail.password} # App password
    properties:
      mail:
        smtp:
          starttls:
            enable: true # startTLS 활성화 여부 (기본값: false)
          auth: true # 사용자 인증 시도 여부 (기본값 : false)
          timeout: ${smtp-timeout} # Socket Read Timeout 시간 (기본값 : 무한)
  data:
    redis:
      host: localhost
      port: 6379
      
# OTP TTL 시간 
redis:
  ttl: ${otp-ttl}

logging:
  level:
    com.bootakhae.userservice: DEBUG

aes:
  spec: ${aes-spec}
  key: ${aes-key}

token:
  secret: ${token-secret}
  access-expired-time: ${access-exp-time}
  refresh-expired-time: ${refresh-exp-time}
