server:
  port: 8082

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: product-service
  profiles:
    active: local
  datasource:
    url: ${url}
    driver-class-name: ${driver-class-name}
    username: ${username_}
    password: ${password}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
#    defer-datasource-initialization: true
#    generate-ddl: true
  data:
    redis:
      host: localhost
      port: 6379
#  sql:
#    init:
#      mode: always

management:
  endpoints:
    web:
      exposure:
        include: info, refresh, health, beans, busrefresh, circuitbreakers

schedule:
  start-time: ${start-time}
  cron: ${cron}

logging:
  level:
    com.bootakhae.productservice: DEBUG