server:
  port: 8082

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: product-service
  rabbitmq:
    host: localhost
    username: ENC(MO+uFEjuYVrQilph19ts8w==)
    password: ENC(mA0wPQIDqWXHfrN9xYDHEA==)
    port: 5672
  datasource:
    url: jdbc:mariadb://localhost:13306/mydb
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  data:
    redis:
      host: localhost
      port: 6379
  sql:
    init:
      mode: never

management:
  endpoints:
    web:
      exposure:
        include: info, refresh, health, beans, busrefresh, circuitbreakers

logging:
  level:
    com.bootakhae.productservice: DEBUG